# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0002_job_is_approved_jobapplication_hr_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrprofile",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Admin tomonidan tasdiqlangan"),
        ),
    ]
