# Generated by Django 6.0.3 on 2026-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_hrprofile_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrprofile',
            options={'verbose_name': 'HR hodim', 'verbose_name_plural': 'HR hodimlar (tasdiqlash)'},
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin tasdiqlagach, HR ish eʼlonlarini joylashi mumkin.', verbose_name='Tasdiqlangan'),
        ),
    ]
